baseurl: /
languageCode: en-us
title: Hugo Ivy
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "帖子"
      url: "/categories/"
      weight: 3
    - name: "标签"
      url: "/tags/"
      weight: 4


params:
  description: "start where you are -     use what you have -     help who you can"
  footer: "&copy; [Yihui Xie](https://yihui.org) 2017-{Year} | [Github](https://github.com/yihui)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
